## NumPy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [5]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9],]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)               #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)    #random

array([0.6402993 , 0.17524897, 0.62790777, 0.51691469, 0.33360061])

In [19]:
np.random.rand(5,5)

array([[0.15849226, 0.39795607, 0.40589552, 0.11318001, 0.53269065],
       [0.47897204, 0.91035394, 0.71220622, 0.09361943, 0.92050607],
       [0.83542264, 0.99628589, 0.02132595, 0.03975328, 0.00875958],
       [0.30090652, 0.50478689, 0.03881336, 0.31759269, 0.11610791],
       [0.78309189, 0.80562975, 0.10544014, 0.53208088, 0.9422689 ]])

In [21]:
np.random.randn(4,4)    # random normal mumbers

array([[-0.81042776,  1.40207256, -0.05282841,  0.48805356],
       [ 0.12212481,  0.74268185,  0.85634483,  0.40143277],
       [-2.79890816,  0.24137676, -1.57310349,  0.63808488],
       [ 0.54464353, -0.35066138, -1.06466501,  0.77910647]])

In [23]:
np.random.randint(1,100,10)  # random integers 

array([79, 51, 35,  5, 74, 66,  3, 46, 48, 44])

In [24]:
ranarr =  np.random.randint(0,50,10)

ranarr

array([49,  8, 47, 13, 34, 39, 43, 39, 22, 29])

In [26]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

49

In [30]:
ranarr.min()

8

In [31]:
ranarr.argmax()

0

In [32]:
ranarr.argmin()

1

In [34]:
arr.shape

(25,)

In [35]:
arr.dtype

dtype('int32')

## Numpy Indexing and Selection

In [37]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[8]

8

In [39]:
arr[1:5]

array([1, 2, 3, 4])

In [40]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [41]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [42]:
 arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[0:5]= 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [47]:
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [48]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_copy = arr.copy()

arr_copy


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing

In [52]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[1,2]

30

In [63]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## Condtional Selection

In [64]:
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
boo_arr  =arr >5
boo_arr 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [68]:
arr[boo_arr]

array([ 6,  7,  8,  9, 10])

In [70]:
arr[arr<3]

array([1, 2])

In [73]:
arr_2d = np.arange(50).reshape(5,10)

arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# NumPy Operations
## Array with Array
## Array with Scalars
## Universal Array Functions

In [78]:
import numpy as np 


In [79]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [81]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [83]:
arr  + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [84]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [85]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [86]:
arr/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_16904\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [87]:
1/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_16904\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [88]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [89]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [90]:
np.max(arr)

10

In [91]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [92]:
np.log(arr)

C:\Users\HP\AppData\Local\Temp\ipykernel_16904\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [95]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [96]:
# Numpy Exercises 

In [97]:
import numpy as np

In [105]:
arr = np.array([0,0,0,0,0,0,0,0,0,0])
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [109]:
arr_1 =  np.array([1,1,1,1,1,1,1,1,1,1])

arr_1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [110]:
arr_5 = np.array([5,5,5,5,5,5,5,5,5,5])

arr_5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [116]:
arr_int = np.arange(10, 50)

arr_int

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [120]:
arr_even = np.arange(10,50,2)

arr_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [122]:
arr = [[0,1,2],[3,4,5],[6,7,8]]

arr = np.array(arr)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
arr = np.eye(3,3)

arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [132]:
normal = np.linspace(0, 25, 10)
normal

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [133]:
np.random.randn(25)

array([ 0.87730274,  0.67136232, -1.1767096 ,  0.5722319 ,  0.55430312,
        1.13520382, -1.64103884,  0.00322048,  0.12455963,  0.29558931,
        0.1858488 ,  1.86780964, -0.52733249, -0.32742896,  2.12809048,
        0.02867874,  0.97816067,  1.28324918,  1.07226218,  0.41136838,
        0.20204734, -0.63787936, -0.72755783,  0.92959391, -1.81881918])

In [134]:
mat = np.arange(1,26).reshape(5,5)

mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [158]:
mat[2:5:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [161]:
mat[3][4]

20

In [162]:
np.sum(mat)

325

In [165]:
np.std(mat)

7.211102550927978

In [170]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])