# Importing Libraries 

In [1]:
#pip install pydot

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 

In [3]:
df = pd.read_csv(r"C:\Users\HP\Downloads\csv cancer.csv")

In [4]:
df.head(2)

Age  Number of sexual partners  First sexual intercourse  \
0   18                          4                        15   
1   15                          1                        14   

   Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
0                   1       0             0.0                  0.0   
1                   1       0             0.0                  0.0   

   Hormonal Contraceptives  Hormonal Contraceptives (years)  IUD  ...  \
0                        0                              0.0    0  ...   
1                        0                              0.0    0  ...   

   STDs:AIDS  STDs:HIV  STDs:Hepatitis B  STDs:HPV  STDs: Number of diagnosis  \
0          0         0                 0         0                          0   
1          0         0                 0         0                          0   

   Dx:Cancer  Dx:CIN  Dx:HPV  Dx  Biopsy  
0          0       0       0   0       0  
1          0       0       0   0       0  

[2 rows x 31 columns]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop('Biopsy',axis = 1)

y = df['Biopsy']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
dtree = DecisionTreeClassifier()

In [10]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [11]:
predictions = dtree.predict(X_test)

In [12]:
from sklearn.metrics import classification_report,confusion_matrix

In [13]:
print(confusion_matrix(y_test,predictions))

print('\n')

print(classification_report(y_test,predictions))

[[207  21]
 [ 13   5]]


              precision    recall  f1-score   support

           0       0.94      0.91      0.92       228
           1       0.19      0.28      0.23        18

    accuracy                           0.86       246
   macro avg       0.57      0.59      0.58       246
weighted avg       0.89      0.86      0.87       246



In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
rfc = RandomForestClassifier(n_estimators= 200)

In [16]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200)

In [17]:
rfc_pred = rfc.predict(X_test)

In [18]:
print(confusion_matrix(y_test,rfc_pred))
print('\n')
print(classification_report(y_test,rfc_pred))

[[226   2]
 [ 14   4]]


              precision    recall  f1-score   support

           0       0.94      0.99      0.97       228
           1       0.67      0.22      0.33        18

    accuracy                           0.93       246
   macro avg       0.80      0.61      0.65       246
weighted avg       0.92      0.93      0.92       246



# Tree Visualization

In [19]:
from IPython.display import Image 
from io import StringIO  # Import StringIO from the io module
from sklearn.tree import export_graphviz
import pydot
features = list(df.columns[1:])

features


['Number of sexual partners',
 'First sexual intercourse',
 'Num of pregnancies',
 'Smokes',
 'Smokes (years)',
 'Smokes (packs/year)',
 'Hormonal Contraceptives',
 'Hormonal Contraceptives (years)',
 'IUD',
 'IUD (years)',
 'STDs',
 'STDs (number)',
 'STDs:condylomatosis',
 'STDs:cervical condylomatosis',
 'STDs:vaginal condylomatosis',
 'STDs:vulvo-perineal condylomatosis',
 'STDs:syphilis',
 'STDs:pelvic inflammatory disease',
 'STDs:genital herpes',
 'STDs:molluscum contagiosum',
 'STDs:AIDS',
 'STDs:HIV',
 'STDs:Hepatitis B',
 'STDs:HPV',
 'STDs: Number of diagnosis',
 'Dx:Cancer',
 'Dx:CIN',
 'Dx:HPV',
 'Dx',
 'Biopsy']

In [20]:
# www.graphviz.org

# Support Vector Machine

In [21]:
from sklearn.svm import SVC 

In [22]:
model = SVC()

In [23]:
model.fit(X_train,y_train)

SVC()

In [24]:
predictions = model.predict(X_test)

In [25]:
from sklearn.metrics import classification_report,confusion_matrix

In [26]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[228   0]
 [ 18   0]]


              precision    recall  f1-score   support

           0       0.93      1.00      0.96       228
           1       0.00      0.00      0.00        18

    accuracy                           0.93       246
   macro avg       0.46      0.50      0.48       246
weighted avg       0.86      0.93      0.89       246



C:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
